import type { Montatore, Cantiere } from './types';

export const MONTATORI_INIZIALI: Montatore[] = [
  { id: 'serban', nome: 'Serban', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'andrei', nome: 'Andrei', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'ion-george', nome: 'Ion', cognome: 'George', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'renato', nome: 'Renato', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'elio', nome: 'Elio', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'robert', nome: 'Robert', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'giovanni', nome: 'Giovanni', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'tony', nome: 'Tony', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'fiore', nome: 'Fiore', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'claudiu', nome: 'Claudiu', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'ghita-marius', nome: 'Ghita', cognome: 'Marius', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'luca', nome: 'Luca', cognome: 'Zanandrea', ditta: 'Quercus S.r.l.', tariffaOraria: 23, tariffaViaggio: 23 },
  { id: 'florin', nome: 'Florin', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'vincenzo', nome: 'Vincenzo', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'mario-evang', nome: 'Mario', cognome: 'Evangelista', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'ovidio', nome: 'Ovidio', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'alex', nome: 'Alexander', cognome: 'Lazarev', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'beniamin', nome: 'Beniamin', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'luigi', nome: 'Luigi', cognome: 'Ippolito', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'ivan', nome: 'Ivan', cognome: 'Comin', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'fratila', nome: 'Fratila', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'ilir', nome: 'Ilir', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'mirko', nome: 'Mirko', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'jose', nome: 'Jose', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'chiru-ionut', nome: 'Chiru', cognome: 'Ionut Denis', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'neculai-ionut', nome: 'Neculai', cognome: 'Ionut Vasile', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'adrian', nome: 'Adrian', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'cosmin', nome: 'Cosmin', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'costantin-petrescu', nome: 'Costantin', cognome: 'Petrescu', ditta: 'Quercus S.r.l.', tariffaOraria: 20, tariffaViaggio: 20 },
  { id: 'fabio', nome: 'Fabio', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 10, tariffaViaggio: 10 },
  { id: 'florin-cristian', nome: 'Florin', cognome: 'Cristian', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'eugen', nome: 'Eugen', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 20, tariffaViaggio: 20 },
  { id: 'stefan-marian', nome: 'Stefan', cognome: 'Marian', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'vanni', nome: 'Vanni', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 22, tariffaViaggio: 22 },
  { id: 'adrian-trautman', nome: 'Adrian', cognome: 'Trautman', ditta: 'Quercus S.r.l.', tariffaOraria: 18, tariffaViaggio: 18 },
  { id: 'costin-adrian', nome: 'Costin', cognome: 'Adrian', ditta: 'Quercus S.r.l.', tariffaOraria: 20, tariffaViaggio: 20 },
  { id: 'matteo', nome: 'Matteo', cognome: '', ditta: 'Quercus S.r.l.', tariffaOraria: 10, tariffaViaggio: 10 },
];

export const CANTIERI_INIZIALI: Cantiere[] = [
  { id: 'vancouver', nome: 'Vancouver', cliente: '', kurzel: 'VAN' },
];
